<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="index.php">Home</a></li>
            <li class="active">Cadastro</li>
        </ul>
    </div>
</div>

<!--Conteudo -->
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div id="formulariocadastro">
                <?php
                    $this->alerta();
                ?>  
                <form action="<?=base_url('')?>/index/cadastro/cliente" method="POST">
                    <div class="row">
                        <div class="form-group col-md-5">
                            <label for="exampleInputEmail1">NOME COMPLETO</label>
                            <input type="text" class="form-control" name="nome" id="exampleInputEmail1" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="InputEmail">E-MAIL</label>
                            <input type="email" class="form-control" name="email" id="email" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputSenha">SENHA</label>
                            <input type="password" class="form-control" name="senha" id="senha" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputReSenha">CONFIRME A SENHA</label>
                            <input type="password" class="form-control" name="ReSenha" id="senha" placeholder="Digite o valor">
                        </div>
                    

                    
                        <div class="form-group col-md-3">
                            <label for="InputCPF">CPF</label>
                            <input type="number" class="form-control" name="cpf" id="cpf" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputdataNasc">DATA DE NASCIMENTO</label>
                            <input type="date" class="form-control" name="dataNasc" id="dataNasc" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputCelular">Nº. CELULAR</label>
                            <input type="celular" class="form-control" name="celular" id="celular" placeholder="Digite o valor">
                        </div>                        
                        <div class="form-group col-md-3">
                            <label for="InputTelefoneFixo">Nº. TELEFONE FIXO</label>
                            <input type="number" class="form-control" name="telefoneFixo" id="telefoneFixo" placeholder="Digite o valor">
                        </div>
                    
                        
                        <div class="form-group col-md-3">
                            <label for="InputCEP">CEP</label>
                            <input type="text" class="form-control" name="cep" id="cep" value="" size="10" maxlength="9"
               onblur="pesquisacep(this.value);">
                        </div>
                        
                        <div class="form-group col-md-6">
                            <label for="InputUF">RUA</label>
                            <input type="text" class="form-control" name="rua" id="rua" >
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputBairro">BAIRRO</label>
                            <input type="text" class="form-control" name="bairro" id="bairro" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputCidade">CIDADE</label>
                            <input type="text" class="form-control" name="cidade" id="cidade" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-1">
                            <label for="InputEstado">ESTADO</label>
                            <input type="text" class="form-control" name="uf" id="uf" >
                        </div>
                        <div class="form-group col-md-5">
                            <label for="InputComplemento">COMPLEMENTO</label>
                            <input type="text" class="form-control" name="complemento" id="complemento" placeholder="Digite o valor">
                        </div>

                    </div>

                    

                    

                    <hr />

                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" name="cadastrar" class="btn btn-primary">Cadastrar</button>
                            <a href="template.html" class="btn btn-default">Cancelar</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<!--Conteudo -->

<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">


            <!-- MAIN -->
            <div id="main" class="col-md-12">


            </div>
            <!-- /MAIN -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->

