<?php
use App\Models\Home\Produtos;
?>

<!-- section -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">                    
                    <div class="col-md-6">                            
                    </div>                   
                    <div class="col-md-12">
                        <div class="order-summary clearfix">
                            <div class="section-title">
                                <h3 class="title">Revisao do Carrinho</h3>
                            </div>
                            <form action="?acao=up" method="POST"> 
                            <table class="shopping-cart-table table">
                                <thead>
                                    <tr>
                                        <th>Produto</th>
                                        <th></th>
                                        <th class="text-center">Preço</th>
                                        <th class="text-center">Quantidade</th>
                                        <th class="text-center">Total</th>
                                        <th class="text-right"></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    <?php
                                    //require_once __DIR__.'/../../Models/Home/Produtos.php';
                                    if (count($_SESSION['carrinho']) == 0) {

                                        echo '<tr><td>Não há produto No carrinho</td></tr>';
                                    } else {

                                        
                                           
                                        foreach ($_SESSION['carrinho'] as $id => $qtd) {
                                            $dados = Produtos::with('Fornecedor')->where("id","=", $id)->get();
                                            $dado = $dados->toArray();

                                            $codigo = $dado[0]['id'];                                            
                                            $nomeProduto = $dado[0]['nomeProduto'];
                                            $qtdEstoque = $dado[0]['qtdEstoque'];
                                            $valor = $dado[0]['valor'];
                                            $foto = $dado[0]['fotoProduto'];
                                            $sub = $dado[0]['valor'] * $qtd;  

                                            echo '<tr>
                <td class="thumb"><img id="foto-checkout" src="' .base_url('/public/img/produtos/'). $foto . '" alt="" width="100" height="80" style="width: 110px; height: 90px; "></td>
                <td class="details">
                        <a href="#">' . $nomeProduto . '</a>											
                </td>
                <td class="price text-center"><strong>R$: ' . $valor . '</strong><br><del class="font-weak"><small>R$: 500.00</small></del></td>
                <td class="qty text-center"><input class="input" type="number" name="prod[' . $id . ']" value="' . $qtd . '" ></td>
                <td class="total text-center"><strong class="primary-color">R$: ' . $sub . '</strong></td>
                <td class="text-right"><a href="?acao=del&id=' . $id . '"><i class="fa fa-close"></i></a></td>
            </tr>
            </tbody>';
                                
//            }
                                        }
                                    }
                                    ?>
                            <tfoot>
                                    <tr>
                                        <th class="empty" colspan="4"></th>
                                        <th colspan="2" class"text-center"><input  class="btn btn-primary" type="submit" value="Atualizar carrinho"> </th>
                                    </tr>
                                    <tr>
                                        <th class="empty" colspan="3"></th>
                                        <th>SUBTOTAL</th>
                                        <th colspan="2" class="sub-total">---</th>
                                    </tr>                                    
                                    <tr>
                                        <th class="empty" colspan="3"></th>
                                        <th>TOTAL</th>
                                        <th colspan="2" class="total">---</th>
                                    </tr>
                                    
                            </tfoot>
                            </table>
                               </form>
                            <div class="pull-right">
                                <a href="<?= base_url('')?>/index"><button class="primary-btn">Voltar as Compras</button></a>
                                <a href="#comprar.php"><button class="primary-btn">Finalizar as compras</button></a>
                            </div>
                        </div>

                    </div>

                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /section -->
