<?php
//if (isset($_GET['sair']) == 'sim') {
//    session_destroy();
//    session_unset();
//     header("Location:" . base_url("") . "/index");
//}

//if(($_SESSION["tipoUsuario"]) <> "comun"){
//    header("Location:" . base_url("") . "/index");
//    exit();
//}
//$sql = "SELECT * FROM Cliente as c JOIN Endereco as e ON c.codigoCliente = e.codigoEndereco WHERE codigoCliente =" . $_SESSION["id"];
//$query = mysqli_query($conn, $sql);
?>



<!--Conteudo -->
<div class="container">
    <div class="row">
        <div class="col-md-11 col-md-offset-1">
            <div id="formularioeditar">
                <div class="row">
                    <!-- STORE -->
                    <div id="store">
                        <!-- row -->
                        <div class="row">
                        </div>
                    </div>
                </div>
                <?php
                $this->alerta();
                
                ?>
                <form action="<?php base_url("")?>/cliente/minhaconta/editar/enviar" method="POST">
                    <div class="row">
                        <input type="hidden" name="id" value="<?= $_SESSION["id"]?>">
                            <?php
                        $this->alerta();
                        foreach ($this->view->Clientes as $exibe) { // Obtém os dados da linha atual e avança para o próximo registro

                            ?>
                        <div class="form-group col-md-5">
                            <label for="exampleInputEmail1">NOME COMPLETO</label>
                            <input type="text" class="form-control" name="nome" id="exampleInputEmail1" value="<?= $exibe['nomeCliente']; ?>" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-4">
                            <label for="InputEmail">E-MAIL</label>
                            <input type="email" class="form-control" name="email" id="email" value="<?= $exibe['email']; ?>" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputSenha">SENHA</label>
                            <input type="password" class="form-control" name="senha" id="senha" value="" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputReSenha">CONFIRME A SENHA</label>
                            <input type="password" class="form-control" name="ReSenha" id="senha" value="" placeholder="Digite o valor">
                        </div>
                    

                    
                        <div class="form-group col-md-3">
                            <label for="InputCPF">CPF</label>
                            <input type="number" class="form-control" name="cpf" id="cpf" value="<?= $exibe['cpf']; ?>" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputdataNasc">DATA DE NASCIMENTO</label>
                            <input type="date" class="form-control" name="dataNasc" id="dataNasc" value="<?= $exibe['dataNas']; ?>" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="InputCelular">Nº. CELULAR</label>
                            <input type="celular" class="form-control" name="celular" id="celular" value="<?= $exibe['celular']; ?>" placeholder="Digite o valor">
                        </div>                        
                        <div class="form-group col-md-3">
                            <label for="InputTelefoneFixo">Nº. TELEFONE FIXO</label>
                            <input type="number" class="form-control" name="telefoneFixo" id="telefoneFixo" value="<?= $exibe['telefoneFixo']; ?>" placeholder="Digite o valor">
                        </div>
                    
                        
                        <div class="form-group col-md-3">
                            <label for="InputCEP">CEP</label>
                            <input type="text" class="form-control" name="cep" id="cep" value="<?= $exibe['endereco']['cep']; ?>" size="10" maxlength="9"
               onblur="pesquisacep(this.value);">
                        </div>
                        
                        <div class="form-group col-md-4">
                            <label for="InputUF">RUA</label>
                            <input type="text" class="form-control" name="rua" id="rua" value="<?= $exibe['endereco']['rua']; ?>">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="InputBairro">BAIRRO</label>
                            <input type="text" class="form-control" name="bairro" id="bairro" value="<?= $exibe['endereco']['bairro']; ?>" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="InputCidade">CIDADE</label>
                            <input type="text" class="form-control" name="cidade" id="cidade" value="<?= $exibe['endereco']['cidade']; ?>" placeholder="Digite o valor">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="InputEstado">ESTADO</label>
                            <input type="text" class="form-control" name="uf" id="uf" value="<?= $exibe['endereco']['estado']; ?>">
                        </div>
                        <div class="form-group col-md-5">
                            <label for="InputComplemento">COMPLEMENTO</label>
                            <input type="text" class="form-control" name="complemento" id="complemento" value="<?= $exibe['endereco']['complemento']; ?>" placeholder="Digite o valor">
                        </div>

                    </div>

                            <?php } ?>
                    </div>                        

                    <div class="row">
                        <div class="col-md-12">
                            <input type="submit" href="<?php base_url('')?>/cliente/minhaconta/editar/enviar" value="Editar" class="btn btn-primary">
                                   
                            <!--<button type="submit" name="editar" class="btn btn-primary"><a href="<?php base_url("")?>/cliente/minhaconta/editar/enviar" >Editar Conta</a></button>-->
                            <!--<a type="submit" href="<?php base_url("")?>/cliente/minhaconta/editar/enviar" class="btn btn-primary">Editar Conta</a>-->                            
                            <a href="<?php base_url("")?>/cliente/minhaconta" class="btn btn-default">Cancelar</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">                    
            <div class="row">
                <!-- STORE -->
                <div id="store">
                    <!-- row -->
                    <div class="row">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!--Conteudo -->

