<!-- section -->
	<div class="section section-grey">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				

				<!-- MAIN -->
				<div id="main" class="col-md-12">
					<!-- store top filter -->
					<div class="store-filter clearfix">
						<div class="pull-left">
							<div class="row-filter">
								<a href="#"><i class="fa fa-th-large"></i></a>
								<a href="#" class="active"><i class="fa fa-bars"></i></a>
							</div>
							
						</div>
						<div class="pull-right">
							
							<ul class="store-pages">
								<li><span class="text-uppercase">Page:</span></li>
								<li class="active">1</li>
								
								<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
							</ul>
						</div>
					</div>
					<!-- /store top filter -->

					<!-- STORE -->
					<div id="store">
						<!-- row -->
						<div class="row">

				<?php                                 
                                
                	foreach ($this->view->Produtos as $produto ) {
                	
                                                  
		                $codigo = $produto['id'];
		                $nomeProduto = $produto['nomeProduto'];
		                $qtdEstoque = $produto['qtdEstoque'];
		                $valor = $produto['valor'];
		                $foto = $produto['fotoProduto'];                             
                 
            			echo '<div class="col-md-4 col-sm-6 col-xs-6">
								<div class="product product-single">
									<div class="product-thumb">
										<div class="product-label">
											<span>New</span>
											<span class="sale">-20%</span>
										</div>
										<button class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</button>
										<img id="imagens" src="'. base_url("")."/public/img/produtos/".$foto.'" alt="">
									</div>
									<div class="product-body">
										<h3 class="product-price">R$: '.$valor.'<del class="product-old-price"></del></h3>
										<div class="product-rating">
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star"></i>
											<i class="fa fa-star-o empty"></i>
										</div>
										<h2 class="product-name"><a href="#">'.$nomeProduto.'</a></h2>
										<div class="product-btns">
											
											<a href="'.base_url('').'/index/checkout?acao=add&id='.$codigo.'"><button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add ao Carinnho</button><a/>
										</div>
									</div>
								</div>
							</div>';
						}
					?>
							
							
							
						</div>
						<!-- /row -->
					</div>
					<!-- /STORE -->

					<!-- store bottom filter -->
					<div class="store-filter clearfix">						
						<div class="pull-right">							
							<ul class="store-pages">
								<li><span class="text-uppercase">Page:</span></li>
								<li class="active">1</li>								
								<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
							</ul>
						</div>
					</div>
					<!-- /store bottom filter -->
				</div>
				<!-- /MAIN -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	
	
	<!-- /section --> 
