<?php

use App\Models\Home\Produtos;

session_start();
//if(!isset($_SESSION)) 
//    { 
//        session_start(); 
//        
//    }

if (isset($_GET['sair']) == 'sim') {
    session_destroy();
    session_unset();
    header("Location:" . base_url("") . "/index");
}



if (!isset($_SESSION['carrinho'])) {
    $_SESSION['carrinho'] = array();
}

//adicionar produto
if (isset($_GET['acao'])) {

    //adicionar produto
    if ($_GET['acao'] == 'add') {
        $id = intval($_GET['id']);
        if (!isset($_SESSION['carrinho'][$id])) {
            $_SESSION['carrinho'][$id] = 1;
        } else {
            $_SESSION['carrinho'][$id] += 1;
        }
    }

    //remover carinho
    if ($_GET['acao'] == 'del') {
        $id = intval($_GET['id']);
        if (isset($_SESSION['carrinho'][$id])) {
            session_destroy();
            unset($_SESSION['carrinho'][$id]);
        }
    }

    //atualizar carrinho
    if ($_GET['acao'] == 'up') {
        if (is_array($_POST['prod'])) {
            foreach ($_POST['prod'] as $id => $qtd) {
                $id = intval($id);
                $qtd = intval($qtd);
                if (!empty($qtd) || $qtd <> 0) {
                    $_SESSION['carrinho'][$id] = $qtd;
                } else {
                    unset($_SESSION['carrinho'][$id]);
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="pt-br">

    <head>
        <!--<meta http-equiv="Content-Type" content="text/html " />-->
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>E-SHOP HTML Template</title>

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/bootstrap.min.css" />

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/slick.css" />
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/slick-theme.css" />

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/nouislider.min.css" />




        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/font-awesome.min.css">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/style.css" />
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/estilo.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link type="text/css" rel="stylesheet" href="<?= base_url("") ?>/public/Home/css/formulariologin.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
                  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
                <![endif]-->


        <!-- Adicionando Javascript -->
        <!-- Adicionando JQuery -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

        <!--         Consultar CEP 
                <script type="text/javascript" src="<?= base_url("") ?>/public/Home/js/consultarCEP.js"></script>
                 Adicionando Javascript 
                <script type="text/javascript" >
        
                    $(document).ready(function () {
        
                        function limpa_formulário_cep() {
                            // Limpa valores do formulário de cep.
                            $("#rua").val("");
                            $("#bairro").val("");
                            $("#cidade").val("");
                            $("#uf").val("");
                            $("#ibge").val("");
                        }
        
                        //Quando o campo cep perde o foco.
                        $("#cep").blur(function () {
        
                            //Nova variável "cep" somente com dígitos.
                            var cep = $(this).val().replace(/\D/g, '');
        
                            //Verifica se campo cep possui valor informado.
                            if (cep != "") {
        
                                //Expressão regular para validar o CEP.
                                var validacep = /^[0-9]{8}$/;
        
                                //Valida o formato do CEP.
                                if (validacep.test(cep)) {
        
                                    //Preenche os campos com "..." enquanto consulta webservice.
                                    $("#rua").val("...");
                                    $("#bairro").val("...");
                                    $("#cidade").val("...");
                                    $("#uf").val("...");
                                    $("#ibge").val("...");
        
                                    //Consulta o webservice viacep.com.br/
                                    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
        
                                        if (!("erro" in dados)) {
                                            //Atualiza os campos com os valores da consulta.
                                            $("#rua").val(dados.logradouro);
                                            $("#bairro").val(dados.bairro);
                                            $("#cidade").val(dados.localidade);
                                            $("#uf").val(dados.uf);
                                            $("#ibge").val(dados.ibge);
                                        } //end if.
                                        else {
                                            //CEP pesquisado não foi encontrado.
                                            limpa_formulário_cep();
                                            alert("CEP não encontrado.");
                                        }
                                    });
                                } //end if.
                                else {
                                    //cep é inválido.
                                    limpa_formulário_cep();
                                    alert("Formato de CEP inválido.");
                                }
                            } //end if.
                            else {
                                //cep sem valor, limpa formulário.
                                limpa_formulário_cep();
                            }
                        });
                    });
        
                </script>        -->

    </head>

    <body>
        <!-- HEADER -->
        <header>        

            <!-- header -->
            <div id="header">
                <div class="container">
                    <div class="pull-left">
                        <!-- Logo -->
                        <div class="header-logo">
                            <a class="logo" href="/index">
                                <h1>Pé-de-Moleque</h1>
                            </a>
                        </div>
                        <!-- /Logo -->                       
                    </div>
                    <div class="pull-right">
                        <ul class="header-btns">
                            <!-- Account -->
                            <li class="header-account dropdown default-dropdown">
                                <div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
                                    <div class="header-btns-icon">
                                        <i class="fa fa-user-o"></i>
                                    </div>
<?php if (isset($_SESSION['logado']) == "sim") { ?>
                                        <strong class="text-uppercase">Minha Conta <i class="fa fa-caret-down"></i></strong>

                                    </div>
                                    <ul class="custom-menu">
                                        <li><a href="<?php base_url("") ?>/cliente/minhaconta"><i class="fa fa-user-o"></i> Minha Conta</a></li>
                                        <li><a href="#"><i class="fa fa-heart-o"></i> Lista de Desejos</a></li>			
                                        <li><a href="#"><i class="fa fa-check"></i> Checkout</a></li>
                                        <li><a href="?sair=sim"><i class="fa fa-unlock-alt"></i> Sair</a></li>					
                                    </ul>
                                <?php } ?>
                                <?php
                                if (isset($_SESSION['logado']) != 'sim') {
                                    ?>
                                <li><a class="text-uppercase" href="<?= base_url('') ?>/index/login">Login</a> / <a class="text-uppercase" href="<?= base_url('') ?>/index/cadastro" >Criar</a></li>
                                <?php
                            }
                            ?>
                            </li>
                            <!-- /Account -->

                            <!-- Cart -->

                            <?php
                            if (count($_SESSION['carrinho']) == 0) {

                                echo ' 
                                                <li class="header-cart dropdown default-dropdown">
                                                <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                                <div class="header-btns-icon">
                                                <i class="fa fa-shopping-cart"></i>
                                                <span class="qty">0</span>
                                                </div>
                                                <strong class="text-uppercase">My Cart:</strong>
                                                <br>                                                
                                                </a>
                                                <div class="custom-menu">
                                                <div id="shopping-cart">
                                                <div class="shopping-cart-list">
                                                    <div class="product product-widget">                                                        
                                                                                                                    
                                                            <h2 class="product-name">Não há produto No carrinho</h2>
                                                                                                               
                                                    </div>
                                                </div>
                                        <div class="shopping-cart-btns">
                                            <button class="main-btn">View Cart</button>
                                            <a href="checkout.php"><button class="primary-btn">Checkout <i class="fa fa-arrow-circle-right"></i></button></a>
                                        </div>
                                    </div>
                                </div>
                            </li>';
                            } else {
                                ?>                   

                                <li class="header-cart dropdown default-dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                        <div class="header-btns-icon">
                                            <i class="fa fa-shopping-cart"></i>
    <?php $quantidade = count($_SESSION['carrinho']); ?>
                                            <span class="qty"><?= $quantidade ?></span>
                                        </div>
                                        <strong class="text-uppercase">My Cart:</strong>
                                        <br>
                                        <span>35.20$</span>
                                    </a>
                                    <div class="custom-menu">
                                        <div id="shopping-cart">
                                            <div class="shopping-cart-list">                                    
                                                <div class="shopping-cart-btns">
                                                    <?php
                                                    foreach ($_SESSION['carrinho'] as $id => $qtd) {

                                                        $dados = Produtos::with('Fornecedor')->where("id", "=", $id)->get();
                                                        $dado = $dados->toArray();
                                                        $codigo = $dado[0]['id'];
                                                        $nomeProduto = $dado[0]['nomeProduto'];
                                                        $qtdEstoque = $dado[0]['qtdEstoque'];
                                                        $valor = $dado[0]['valor'];
                                                        $foto = $dado[0]['fotoProduto'];
                                                        $sub = $dado[0]['valor'] * $qtd;

                                                        echo '<div class="product product-widget">
            <div class="product-thumb">
              <img src="' . base_url('/public/img/produtos/') . $foto . '" alt="" width="100" height="50">
             </div>
            <div class="product-body">
                <h3 class="product-price">R$: ' . $valor . '<span class="qty"></span></h3>
                <h2 class="product-name"><a href="#">' . $nomeProduto . '</a></h2>
                 </div>
                <button class="cancel-btn"><a href="?acao=del&id=' . $id . '"><i class="fa fa-trash"></i></a></button>
                </div>                
                 ';
                                                    }
                                                    ?>
                                                    <button class="main-btn">View Cart</button>
                                                    <a href="checkout.php"><button class="primary-btn">Checkout <i class="fa fa-arrow-circle-right"></i></button></a>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                        </div>
                                    </div>
                            </li>
                            <!-- /Cart -->

                            <!-- Mobile nav toggle-->
                            <li class="nav-toggle">
                                <button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
                            </li>
                            <!-- / Mobile nav toggle -->
                        </ul>
                    </div>
                </div>
                <!-- header -->
            </div>
            <!-- container -->
        </header>
        <!-- /HEADER -->

        <!-- NAVIGATION -->
        <div id="navigation">
            <!-- container -->
            <div class="container">
                <div id="responsive-nav">


                    <!-- menu nav -->
                    <div class="menu-nav">
                        <span class="menu-header">Menu <i class="fa fa-bars"></i></span>
                        <ul class="menu-list">                           
                            <li><a href="<?= base_url(''); ?>/index">Shop</a></li>			
                        </ul>
                    </div>
                    <!-- menu nav -->
                </div>
            </div>
            <!-- /container -->
        </div>
        <!-- /NAVIGATION -->

        <!--Conteudo-->
<?php $this->content() ?>
        <!--Fim Conteudo-->        
        <!-- FOOTER -->
        <footer id="footer" class="section section-grey">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <!-- footer widget -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer">
                            <!-- footer logo -->
                            <div class="footer-logo">
                                <a class="logo" href="#">
                                    <h3>Pé-De-Moleque</h3>
                                </a>
                            </div>
                            <!-- /footer logo -->

                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>

                            <!-- footer social -->
                            <ul class="footer-social">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                            </ul>
                            <!-- /footer social -->
                        </div>
                    </div>
                    <!-- /footer widget -->

                    <!-- footer widget -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-header">My Account</h3>
                            <ul class="list-links">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">My Wishlist</a></li>
                                <li><a href="#">Compare</a></li>
                                <li><a href="#">Checkout</a></li>
                                <li><a href="<?= base_url('') ?>/index/login">Login</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /footer widget -->

                    <div class="clearfix visible-sm visible-xs"></div>

                    <!-- footer widget -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-header">Customer Service</h3>
                            <ul class="list-links">
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Shiping & Return</a></li>
                                <li><a href="#">Shiping Guide</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /footer widget -->

                    <!-- footer subscribe -->
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-header">Stay Connected</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
                            <form>
                                <div class="form-group">
                                    <input class="input" placeholder="Enter Email Address">
                                </div>
                                <button class="primary-btn">Join Newslatter</button>
                            </form>
                        </div>
                    </div>
                    <!-- /footer subscribe -->
                </div>
                <!-- /row -->
                <hr>
                <!-- row -->
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center">
                        <!-- footer copyright -->
                        <div class="footer-copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                        <!-- /footer copyright -->
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </footer>
        <!-- /FOOTER -->

        <!-- jQuery Plugins -->
        <script src="<?= base_url('') ?>/public/Home/js/jquery.min.js"></script>
        <script src="<?= base_url('') ?>/public/Home/js/bootstrap.min.js"></script>
        <script src="<?= base_url('') ?>/public/Home/js/slick.min.js"></script>
        <script src="<?= base_url('') ?>/public/Home/js/nouislider.min.js"></script>
        <script src="<?= base_url('') ?>/public/Home/js/jquery.zoom.min.js"></script>
        <script src="<?= base_url('') ?>/public/Home/js/main.js"></script>


    </body>

</html>